In [1]:
import re
import pandas as pd

In [2]:
f = open("_chat.txt",'r', encoding='utf-8')
data = f.read()

In [3]:
print(data)

[19/08/23, 7:53:34 PM] abhay: ‎Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them.
[19/08/23, 7:53:34 PM] abhay: .
[19/08/23, 7:53:39 PM] Abhishek jha_20233504: https://www.instagram.com/reel/Cv_67H3otmN/?igshid=MzRlODBiNWFlZA==
‎[19/08/23, 7:55:03 PM] abhay: ‎video omitted
[22/08/23, 5:26:00 PM] abhay: Abey hostel me light aa rahi hai kya
[22/08/23, 5:50:34 PM] Abhishek jha_20233504: yes bro
[22/08/23, 5:57:51 PM] abhay: ‎This message was deleted.
[28/08/23, 10:32:50 PM] Abhishek jha_20233504: bro
[28/08/23, 10:33:00 PM] Abhishek jha_20233504: turn on the hotspot 🥹
[28/08/23, 10:33:03 PM] Abhishek jha_20233504: for me
[28/08/23, 10:33:18 PM] Abhishek jha_20233504: Axa khula huwa hi hain
[10/09/23, 2:32:21 PM] abhay: https://colab.research.google.com/drive/1NDBWpKLM9CV18h2bLyQjnjSLIq0acTGt
[17/09/23, 11:48:27 PM] abhay: https://colab.research.google.com/drive/1GOqgrB7GVGwEEAzt40vZG-mY2yTe8cCS?usp=sharing
[21/09/23, 7:17:45 PM] abhay: ‎Missed voice call
‎[26/09/23, 4:38:45 PM] abhay: CSED-1(Computer programing)-20230823T044424Z-001.zip ‎document omitted
[26/09/23, 4:38:52 PM] abhay: isme notes me jaana
[26/09/23, 11:15:58 PM] abhay: scope of a variable

call by value call by address

what is loop

while loop and for loop what is advantage of switch over if else what is the use of conditional operators int and float (2 to the power till 16) what is the use of break first 15 questions from (chapter 2,3,4,5) (outputs)

classwork questions what is recursion?
[26/09/23, 11:16:00 PM] Abhishek jha_20233504: scope of a variable
call by value call by address what is loop
while loop and for loop
what is advantage of switch over if else what is the use of conditional operators int and float (2 to the power till 16)
what is the use of break
‎[26/09/23, 11:28:47 PM] abhay: ‎image omitted
‎[26/09/23, 11:28:58 PM] abhay: ‎image omitted
‎[26/09/23, 11:29:10 PM] abhay: ‎image omitted
‎[26/09/23, 11:40:53 PM] abhay: ‎image omitted
‎[03/10/23, 8:05:26 PM] abhay: calculus maths20231003 20.5.00.pdf • ‎21 pages ‎document omitted
‎[05/10/23, 9:31:02 PM] abhay: ‎image omitted
[11/10/23, 12:32:47 AM] Abhishek jha_20233504: bhai
[11/10/23, 12:32:51 AM] Abhishek jha_20233504: kuch khane chale
[11/10/23, 12:32:58 AM] Abhishek jha_20233504: 🥹
[11/10/23, 12:33:04 AM] abhay: So jaa
[11/10/23, 12:33:11 AM] Abhishek jha_20233504: zimzam
[11/10/23, 12:33:22 AM] Abhishek jha_20233504: 🥹
[11/10/23, 12:33:22 AM] abhay: Bhai neend aa raha
[11/10/23, 12:33:28 AM] Abhishek jha_20233504: 2 min lagega
[11/10/23, 12:33:40 AM] abhay: So jaa
[11/10/23, 12:33:52 AM] abhay: Fir neend toot jaayega
[11/10/23, 12:34:13 AM] Abhishek jha_20233504: chapal bhi tere room meh hain
[14/10/23, 9:45:43 AM] Abhishek jha_20233504: bhai
[14/10/23, 9:45:44 AM] Abhishek jha_20233504: sunnaa
‎[14/10/23, 10:10:22 AM] abhay: ‎image omitted
‎[15/10/23, 4:04:22 PM] abhay: Here are my UPI details
Name - Abhay Sachan  So  Rajiv Kumar Sachan
UPI Handle - 918318656396@paytm ‎image omitted
[17/10/23, 2:10:06 PM] Abhishek jha_20233504: bhai
[17/10/23, 2:10:21 PM] Abhishek jha_20233504: ish period ka attendce kardena
[17/10/23, 2:10:22 PM] Abhishek jha_20233504: plz
[17/10/23, 2:10:29 PM] Abhishek jha_20233504: next class meh atta hoon
[17/10/23, 2:12:43 PM] abhay: Ok
[17/10/23, 2:13:20 PM] Abhishek jha_20233504: xorde,ek dusre ko kehdiya hain
[17/10/23, 2:13:27 PM] abhay: Ok
‎[18/10/23, 7:23:08 PM] Abhishek jha_20233504: binarySearch.c ‎document omitted
‎[18/10/23, 7:23:08 PM] Abhishek jha_20233504: bubble.c ‎document omitted
‎[18/10/23, 7:23:08 PM] Abhishek jha_20233504: bubble2.c ‎document omitted
‎[18/10/23, 7:23:08 PM] Abhishek jha_20233504: InsertionSort.c ‎document omitted
‎[18/10/23, 7:23:08 PM] Abhishek jha_20233504: minmax.c ‎document omitted
‎[18/10/23, 7:23:09 PM] Abhishek jha_20233504: output.pdf • ‎8 pages ‎document omitted
‎[18/10/23, 7:23:09 PM] Abhishek jha_20233504: reverse1.c ‎document omitted
‎[18/10/23, 7:23:09 PM] Abhishek jha_20233504: reverse2.c ‎document omitted
‎[18/10/23, 7:23:09 PM] Abhishek jha_20233504: sectionsort.c ‎document omitted
[18/10/23, 11:43:17 PM] Abhishek jha_20233504: payment hogya bhai
[19/10/23, 8:09:38 AM] Abhishek jha_20233504: id:abhishek16
password:Abhishek16@
[19/10/23, 10:26:03 AM] Abhishek jha_20233504: bhai sunna
[19/10/23, 10:26:50 AM] abhay: Bol
[19/10/23, 10:27:23 AM] Abhishek jha_20233504: 50 pay kardega bhai,khula nahi hain,Tujhe meh bhaiya se karadunga apne khate ka pay🥹
‎[19/10/23, 10:27:29 AM] Abhishek jha_20233504: ‎image omitted
[19/10/23, 10:27:46 AM] Abhishek jha_20233504: ye dokan wala 500 ka khula nahi kar rha
[19/10/23, 10:27:54 AM] Abhishek jha_20233504: Raste meh hoon
[19/10/23, 10:28:02 AM] abhay: Ruk acha
[19/10/23, 10:28:19 AM] Abhishek jha_20233504: hogya?
[19/10/23, 10:28:35 AM] abhay: 2 min lagega
[19/10/23, 10:28:41 AM] Abhishek jha_20233504: abe
[19/10/23, 10:28:44 AM] Abhishek jha_20233504: bus nikalne wala hain
[19/10/23, 10:28:47 AM] Abhishek jha_20233504: haldi
[19/10/23, 10:28:53 AM] Abhishek jha_20233504: jaldi
[19/10/23, 10:29:23 AM] abhay: Shyamu naam hai
[19/10/23, 10:29:34 AM] Abhishek jha_20233504: ha
[19/10/23, 10:29:39 AM] Abhishek jha_20233504: bhai
[19/10/23, 10:29:59 AM] abhay: Pooch
[19/10/23, 10:30:12 AM] abhay: Ho raha
[19/10/23, 10:30:41 AM] Abhishek jha_20233504: huwa?
[19/10/23, 10:31:00 AM] abhay: Abe class me net nhii chal raha processing me hai
[19/10/23, 10:31:13 AM] abhay: Ho gaya
[19/10/23, 10:38:47 AM] Abhishek jha_20233504: 😍😍😍😍
[19/10/23, 10:06:26 PM] Abhishek jha_20233504: bhai
[19/10/23, 10:07:14 PM] Abhishek jha_20233504: assignment?
[19/10/23, 10:08:40 PM] abhay: Kar diya hai week 5 ka
[19/10/23, 10:08:45 PM] abhay: Abhi week 6 ka
[19/10/23, 10:08:59 PM] Abhishek jha_20233504: Thankyou bhai🥹🥹🥹
[19/10/23, 10:32:48 PM] abhay: Tera week 6 bhi kar diya
[19/10/23, 10:36:06 PM] Abhishek jha_20233504: 🥹🥹🥹🥹
[19/10/23, 10:36:34 PM] abhay: Week 5 me teri output reh gayi thu
[19/10/23, 10:36:40 PM] abhay: Usko baad me Kari thi
[19/10/23, 10:36:53 PM] Abhishek jha_20233504: ye le chuma😘
‎[19/10/23, 10:37:00 PM] abhay: ‎sticker omitted
[19/10/23, 10:37:31 PM] abhay: Kaha hai tu abhi
[19/10/23, 10:37:53 PM] Abhishek jha_20233504: pata nahi bhai bas chale ja rahe hain
[19/10/23, 10:38:06 PM] abhay: 😂😂
[19/10/23, 10:38:25 PM] abhay: Chalo subah Tak pahucha degi
‎[22/10/23, 6:37:04 AM] Abhishek jha_20233504: ‎image omitted
[22/10/23, 6:37:11 AM] Abhishek jha_20233504: iska matlab kya hota hain
[22/10/23, 9:08:17 AM] abhay: 23 ko last date hai assignment submit karne ki
[22/10/23, 9:18:20 AM] Abhishek jha_20233504: mera toh hogya haina,
[22/10/23, 9:21:58 AM] abhay: AIML wala hai ye
[22/10/23, 9:22:22 AM] Abhishek jha_20233504: bhai woh bhi karde🥹,Gau pe hoon
[22/10/23, 9:22:47 AM] abhay: https://colab.research.google.com/drive/1SX819z-zcUd3e4FklSmYW1GjVQMSS001#scrollTo=ML3mP28lKQpv
[22/10/23, 9:22:57 AM] abhay: Isme. Name change karde
[22/10/23, 9:23:01 AM] abhay: Thoda edit karde
[22/10/23, 9:23:08 AM] abhay: Upload karde classroom.me
[22/10/23, 9:23:28 AM] Abhishek jha_20233504: areh mere pass laptop bhi nahi hain abhi,Gau pe hoon,30 mb pe chala rha hoon
[22/10/23, 9:23:37 AM] Abhishek jha_20233504: 🥹
[22/10/23, 9:24:19 AM] abhay: Abe to Google classroom ke liye account chaiye
[22/10/23, 9:24:35 AM] abhay: Abhishek pachlaniya se bol de
[22/10/23, 9:24:42 AM] Abhishek jha_20233504: Thik hain bro
[22/10/23, 9:24:45 AM] abhay: Uske me Tera login hai
[30/10/23, 12:01:42 PM] Abhishek jha_20233504: paper suna diya?
[30/10/23, 12:01:45 PM] Abhishek jha_20233504: ethics ka?
[30/10/23, 12:07:17 PM] abhay: Haa
[30/10/23, 12:07:28 PM] abhay: But tera dekh nhii paaya
[30/10/23, 12:07:31 PM] Abhishek jha_20233504: mera attendence lagaya?
[30/10/23, 12:07:36 PM] abhay: Bahut kam bache the
[30/10/23, 12:07:38 PM] abhay: Naa
[30/10/23, 12:07:41 PM] Abhishek jha_20233504: chutiya
[30/10/23, 12:07:44 PM] Abhishek jha_20233504: kamina
[30/10/23, 12:07:47 PM] abhay: Bache hi nhii the saale
[30/10/23, 12:08:05 PM] abhay: Start ke 20 me bas 3 bache the
[30/10/23, 12:08:26 PM] abhay: Poore A1 me 14 bache aaye the
[30/10/23, 12:08:29 PM] Abhishek jha_20233504: 1 nov ko aaunga,Aab direct november se padhai suru😂
[30/10/23, 12:08:33 PM] Abhishek jha_20233504: Axa axa
[30/10/23, 12:08:46 PM] Abhishek jha_20233504: roj ka 6 6 ghante padhenge
[30/10/23, 12:09:04 PM] abhay: Bilkul ab se ekdum serious 😂🤣
[30/10/23, 12:09:29 PM] Abhishek jha_20233504: pura november achese padhlenge fhir december me mast se exam sab denge aur winter holiday khusi. khusi manayenge
[30/10/23, 12:09:32 PM] Abhishek jha_20233504: plan fixed
‎[30/10/23, 12:09:43 PM] abhay: ‎sticker omitted
[30/10/23, 12:10:05 PM] Abhishek jha_20233504: You also join okay brother,dono sath me 9 cgpa layenge
[30/10/23, 12:10:10 PM] Abhishek jha_20233504: 🤝
[30/10/23, 12:10:15 PM] Abhishek jha_20233504: aag laga denge aag
‎[30/10/23, 12:10:49 PM] abhay: ‎sticker omitted
[30/10/23, 12:11:05 PM] Abhishek jha_20233504: ha yese hi😂
‎[30/10/23, 12:11:12 PM] abhay: ‎sticker omitted
‎[01/11/23, 9:04:47 PM] abhay: ‎video omitted
‎[01/11/23, 9:04:47 PM] abhay: ‎image omitted
‎[01/11/23, 9:05:10 PM] abhay: ‎video omitted
‎[01/11/23, 9:05:19 PM] abhay: ‎video omitted
‎[01/11/23, 9:08:36 PM] abhay: ‎video omitted
‎[07/11/23, 6:23:45 PM] abhay: ‎image omitted
[08/11/23, 8:53:17 PM] Abhishek jha_20233504: https://drive.google.com/file/d/1EeTid4Sn9QeicbvrykI16KABDYigmH1e/view?usp=drivesdk
‎[16/11/23, 9:23:19 AM] abhay: integral calculus.pdf • ‎14 pages ‎document omitted
‎[16/11/23, 9:31:01 AM] abhay: maths20230911 16.31.38.pdf • ‎34 pages ‎document omitted
‎[16/11/23, 9:34:27 AM] abhay: DOC-20231003-WA0015. • ‎21 pages ‎document omitted
‎[18/11/23, 1:23:50 PM] Abhishek jha_20233504: ‎image omitted
‎[18/11/23, 1:29:24 PM] Abhishek jha_20233504: ‎image omitted
‎[18/11/23, 1:29:27 PM] Abhishek jha_20233504: ‎image omitted
‎[18/11/23, 1:29:33 PM] Abhishek jha_20233504: ‎image omitted
[23/11/23, 9:56:45 AM] Abhishek jha_20233504: ‎Voice call, ‎10 sec
‎[23/11/23, 9:57:18 AM] Abhishek jha_20233504: ‎image omitted
[23/11/23, 9:57:28 AM] Abhishek jha_20233504: jaldi
[23/11/23, 9:57:54 AM] Abhishek jha_20233504: jaldi
[23/11/23, 9:58:06 AM] abhay: Done
‎[23/11/23, 9:58:43 AM] abhay: Paid on Paytm. Check your payment history here:
https://m.paytm.me/passbook_landing ‎image omitted
[24/11/23, 5:00:48 PM] abhay: Abhay sachan 20233008
[24/11/23, 5:00:57 PM] abhay: Abhishek 20233013
[24/11/23, 5:16:51 PM] abhay: No dikha raha  kya
[24/11/23, 5:16:55 PM] abhay: Ye bata
[24/11/23, 5:17:06 PM] Abhishek jha_20233504: nahi bhai
[24/11/23, 5:17:08 PM] abhay: Akshai bala 20233507
‎[25/11/23, 9:02:05 PM] Abhishek jha_20233504: ‎image omitted
[25/11/23, 9:02:15 PM] Abhishek jha_20233504: bro isko 50 karde
[25/11/23, 9:03:24 PM] abhay: kar diye
‎[26/11/23, 9:03:18 PM] Abhishek jha_20233504: ‎image omitted
[26/11/23, 9:03:18 PM] Abhishek jha_20233504: isko 40 karde,Aaj 500 hojayega,room pe aake direct 500 dedunga
[28/11/23, 5:47:07 PM] Abhishek jha_20233504: bhai
[28/11/23, 5:47:23 PM] Abhishek jha_20233504: assignment 3 ka note vhejde jaldi
[28/11/23, 5:47:26 PM] Abhishek jha_20233504: solution
[28/11/23, 5:53:38 PM] abhay: Nhii hai mere pass
[28/11/23, 7:19:31 PM] Abhishek jha_20233504: bhai
[28/11/23, 7:19:59 PM] Abhishek jha_20233504: bro
[28/11/23, 7:20:14 PM] Abhishek jha_20233504: sunna
[28/11/23, 7:20:21 PM] Abhishek jha_20233504: ‎Voice call, ‎No answer
[28/11/23, 7:20:35 PM] Abhishek jha_20233504: bhai
[28/11/23, 7:20:37 PM] abhay: Bol
[28/11/23, 7:20:46 PM] Abhishek jha_20233504: goyal pe 20 payment karde plz
[28/11/23, 7:20:51 PM] Abhishek jha_20233504: QR vhejrha hoon
‎[28/11/23, 7:21:05 PM] Abhishek jha_20233504: ‎image omitted
[28/11/23, 7:21:24 PM] Abhishek jha_20233504: jaldi
[28/11/23, 7:21:35 PM] abhay: Ok
[28/11/23, 7:21:41 PM] Abhishek jha_20233504: hogya?
[28/11/23, 7:22:01 PM] Abhishek jha_20233504: done?
[28/11/23, 7:22:07 PM] Abhishek jha_20233504: huwa?
[28/11/23, 7:22:20 PM] Abhishek jha_20233504: jaldi karna
[28/11/23, 7:22:21 PM] Abhishek jha_20233504: sale
[28/11/23, 7:22:51 PM] abhay: ho gya
‎[28/11/23, 7:23:02 PM] abhay: Paid on Paytm. Check your payment history here:
https://m.paytm.me/passbook_landing ‎image omitted
[28/11/23, 10:19:33 PM] abhay: https://www.vijaysales.com/hp-victus-gaming-laptop-15-fa0998tx-12th-gen-core-i5-16gb-ram-512-gb-ssd-15-6-inch-39-62-cm-display-4-gb-rtx-graphics-win-11-office/24048
[03/12/23, 10:24:11 PM] abhay: AI ML ASSIGNMENTS

1-pdf
2-https://colab.research.google.com/drive/1--4VFFcxVnry0HqgQxXPENYxIJAeIJI8
3-https://colab.research.google.com/drive/1zpcGp89NyaIF3GSJMcO5_voswi82vANb
4-https://colab.research.google.com/drive/1CkY9Hkp3CYi429_XahXnMslNI1hgkqsX
5-https://colab.research.google.com/drive/1SX819z-zcUd3e4FklSmYW1GjVQMSS001
6-https://colab.research.google.com/drive/1jGeEIfL4DPGR42ht9y5hPD8MYU6L0k_B
7-https://colab.research.google.com/drive/1ko1PIDGpXcm8HF2JaCxY3X3GSZCvvqTi
8-https://colab.research.google.com/drive/1-8XFVMQJJTutMPSpV3eJLLGqQQjBLegB
9-https://colab.research.google.com/drive/1kNpyOJ7ueI9TyuRyYZlQ_o5iQVym0hOE
10-https://colab.research.google.com/drive/1zRrI_gavWxiygAI5OawtUx4AafnYxKaf
[03/12/23, 11:21:28 PM] abhay: import pandas as pd
dic={"days":["monday","tuesday","wednesday","thursday","friday","satarday","sunday"],"rainfall":[]}
l=eval(input("Enter rainfall in list :"))
dic["rainfall"]=l
df=pd.DataFrame(dic)
print(df)
df.describe()
[10/12/23, 12:56:18 PM] Abhishek jha_20233504: ‎Voice call, ‎No answer
[10/12/23, 12:56:28 PM] Abhishek jha_20233504: sunna
[10/12/23, 12:56:32 PM] abhay: Bol
[10/12/23, 12:56:36 PM] Abhishek jha_20233504: math ka ode ka syllabus kya hain
[10/12/23, 12:56:41 PM] Abhishek jha_20233504: wo vhejdeto
[10/12/23, 12:56:44 PM] Abhishek jha_20233504: ek dost ko vhejna hain
[10/12/23, 12:56:47 PM] abhay: Nhii pata
[14/12/23, 7:28:59 PM] abhay: https://drive.google.com/drive/folders/16tVRfXYVJZbtxcnmCEI8fw_dT48zUx0I
[15/12/23, 3:37:52 PM] Abhishek jha_20233504: main( )
§
statie int ar 1 = do,12,3,47
int *xpt= P;
Statte int *pls- fa, atls ar 2, arsatrz,
Ato ++;
point Cuy d y.dled in", ptor p, xptr-a, +* ptr);
*pfp ++;
printf ("-d % d 1.d In", Pts p, aptora; xxptr);
*++php
printf ("'4 %4 '%. d in'", ptr-P, xeptr-a xApte);
++ *ptp;
printf ("%. d%.d/etIn", pto-p, * pto-a, xxptro),;
[26/12/23, 3:29:04 PM] Abhishek jha_20233504: highest package
[26/12/23, 3:31:10 PM] abhay: 🥳😂
[07/01/24, 1:08:01 PM] Abhishek jha_20233504: https://www.amazon.in/Led-Strip-Metalled-Multicolour-Waterproof/dp/B0BD5SYDNT/ref=sr_1_33?crid=3FPMZQWBA6F9P&keywords=rgb%2Bmulti%2Bcolour%2Bled%2Blight&qid=1704612940&sprefix=rgb%2Bmul%2Caps%2C235&sr=8-33&th=1
[07/01/24, 1:09:22 PM] Abhishek jha_20233504: https://www.amazon.in/Syvo-3130-Aluminum-Universal-Lightweight/dp/B07N42JB4S/ref=sr_1_3?crid=289JQWNX38EBC&keywords=tripod&qid=1704613140&sprefix=tripod%2Caps%2C207&sr=8-3&th=1
[07/01/24, 1:14:01 PM] Abhishek jha_20233504: https://www.amazon.in/JBL-Commercial-Omnidirectional-Microphone-Conferences/dp/B08SCG35MG/ref=sr_1_7?crid=AGPWQYM7OCEK&keywords=mic&qid=1704613168&sprefix=mic%2Caps%2C217&sr=8-7&th=1
‎[11/01/24, 12:02:30 PM] abhay: ‎image omitted
[11/01/24, 10:52:14 PM] Abhishek jha_20233504: ‎Voice call, ‎No answer
[11/01/24, 11:46:38 PM] Abhishek jha_20233504: ‎Voice call, ‎No answer
‎[17/01/24, 10:41:21 PM] abhay: ‎image omitted
[18/01/24, 3:41:51 PM] Abhishek jha_20233504: ‎Voice call, ‎1 min
[18/01/24, 3:43:12 PM] Abhishek jha_20233504: NLH1?
[19/01/24, 10:29:14 AM] abhay: ‎Missed voice call, ‎Tap to call back
[23/01/24, 11:56:01 PM] Abhishek jha_20233504: ‎Voice call, ‎20 sec
[23/01/24, 11:56:46 PM] Abhishek jha_20233504: kuch kha lete toh acha hota
[24/01/24, 8:50:47 AM] Abhishek jha_20233504: ‎Voice call, ‎4 sec
[25/01/24, 1:03:34 PM] Abhishek jha_20233504: ‎Voice call, ‎No answer
‎[30/01/24, 8:03:08 PM] Abhishek jha_20233504: ‎image omitted
[30/01/24, 8:03:12 PM] Abhishek jha_20233504: 120 karde
‎[30/01/24, 8:03:20 PM] Abhishek jha_20233504: ‎image omitted
[30/01/24, 8:03:25 PM] Abhishek jha_20233504: ‎Voice call, ‎16 sec
[30/01/24, 8:04:12 PM] Abhishek jha_20233504: Quick
[30/01/24, 8:05:19 PM] abhay: Done
[30/01/24, 8:10:57 PM] Abhishek jha_20233504: Thanks bro
[30/01/24, 8:10:59 PM] Abhishek jha_20233504: love you
[30/01/24, 8:22:35 PM] abhay: ‎This message was deleted.
[02/02/24, 7:51:03 PM] abhay: Apne Gharwalo ko call karle phone aaya tha unka
[06/02/24, 6:13:07 PM] abhay: 5,6, and 16-19
[06/02/24, 6:13:13 PM] abhay: Itne karne hai tujhe
‎[10/02/24, 4:56:20 PM] abhay: ‎image omitted
[10/02/24, 6:53:30 PM] Abhishek jha_20233504: ‎You deleted this message.
[10/02/24, 6:53:36 PM] Abhishek jha_20233504: ‎You deleted this message.
[10/02/24, 6:53:41 PM] Abhishek jha_20233504: ‎You deleted this message.
‎[11/02/24, 11:47:20 PM] abhay: Abhishek kumar jha.pdf • ‎39 pages ‎document omitted
[13/02/24, 11:30:49 PM] abhay: sun
[13/02/24, 11:30:54 PM] Abhishek jha_20233504: sunna
[13/02/24, 11:31:00 PM] abhay: jo tune DS ka assignment bheja hai
[13/02/24, 11:31:11 PM] abhay: wo bhi copy me karke submit karna hai
[13/02/24, 11:31:30 PM] abhay: aur agar yahi bc chalti rahi to mai copy me karunga
[13/02/24, 11:31:33 PM] abhay: file me nhii
[13/02/24, 11:32:03 PM] Abhishek jha_20233504: kya?
[13/02/24, 11:32:25 PM] Abhishek jha_20233504: okay bro
[13/02/24, 11:32:35 PM] abhay: abe pooch raha hu
‎[13/02/24, 11:32:54 PM] abhay: Assignment-2.pdf • ‎1 page ‎document omitted
[13/02/24, 11:33:14 PM] abhay: ye wala
[13/02/24, 11:33:20 PM] abhay: sir ne kuch bola hai
[13/02/24, 11:33:27 PM] abhay: handwritten wali bc
[13/02/24, 11:33:42 PM] abhay: ye bkl jaha dikh jaata hai gussa hi aata hai mereko
[13/02/24, 11:37:20 PM] Abhishek jha_20233504: Aayein?
[13/02/24, 11:38:32 PM] abhay: ‎Voice call, ‎12 sec
[17/02/24, 3:59:48 PM] Abhishek jha_20233504: ‎Voice call, ‎54 sec
[17/02/24, 4:26:37 PM] abhay: Saale agar seniors ho to mat khulwana gate
[17/02/24, 9:30:24 PM] abhay: saale kidhar hai
[17/02/24, 9:30:34 PM] abhay: mera phone leke gaya hai
[17/02/24, 9:30:41 PM] abhay: aur mere earpods bhi
[17/02/24, 9:30:53 PM] abhay: pitega tu merese😠
[17/02/24, 9:35:09 PM] Abhishek jha_20233504: 😘😘
[17/02/24, 9:35:42 PM] abhay: 😖😖
[17/02/24, 9:35:53 PM] abhay: bhai padhai karni hai
[19/02/24, 10:25:01 AM] abhay: Oii
[19/02/24, 10:25:18 AM] Abhishek jha_20233504: habbhai
[19/02/24, 10:25:46 AM] abhay: Tera proxy lagana hai?
[19/02/24, 10:25:54 AM] Abhishek jha_20233504: ha bhai
[19/02/24, 10:25:56 AM] abhay: 🥺🥺
[19/02/24, 10:26:01 AM] Abhishek jha_20233504: jaroori hain
[19/02/24, 10:26:04 AM] abhay: Dekhte hai
[19/02/24, 10:26:07 AM] Abhishek jha_20233504: bohot din badh kaha hoon
[19/02/24, 10:26:08 AM] Abhishek jha_20233504: mene
[19/02/24, 10:26:16 AM] Abhishek jha_20233504: karde
[19/02/24, 10:26:50 AM] abhay: . ‎<This message was edited>
[19/02/24, 10:27:01 AM] abhay: Thik hai laga dega 🥲🥲
[19/02/24, 5:48:55 PM] Abhishek jha_20233504: Ajana
[19/02/24, 5:48:58 PM] Abhishek jha_20233504: Jaldi!
[19/02/24, 5:49:04 PM] Abhishek jha_20233504: 6:00 pm tak
[19/02/24, 6:03:54 PM] abhay: Class me hu abhi
[19/02/24, 6:19:02 PM] abhay: Waha hai kya
[19/02/24, 6:19:09 PM] abhay: Aur start kab hoga
‎[19/02/24, 11:42:43 PM] abhay: ds assignment.pdf • ‎10 pages ‎document omitted
[20/02/24, 12:31:43 AM] Abhishek jha_20233504: ‎Voice call, ‎No answer
[20/02/24, 5:43:59 PM] Abhishek jha_20233504: aaj seminar hall ajana
[20/02/24, 5:49:44 PM] abhay: Try
[20/02/24, 5:56:29 PM] Abhishek jha_20233504: areh ajana
[20/02/24, 5:56:33 PM] Abhishek jha_20233504: briefing lite lo
[20/02/24, 5:56:41 PM] Abhishek jha_20233504: 15,20 min me aja
[20/02/24, 6:09:45 PM] abhay: abe 7 baje hai na
[20/02/24, 6:09:56 PM] Abhishek jha_20233504: usko lite lo
[20/02/24, 6:10:00 PM] abhay: aur man to nhii hai mera
[20/02/24, 6:10:09 PM] abhay: acha
[20/02/24, 6:10:24 PM] Abhishek jha_20233504: Ajao
[20/02/24, 6:10:25 PM] abhay: seminar hall me kya hi karwayenge
[20/02/24, 6:10:32 PM] Abhishek jha_20233504: idhar refreshment bhi hain

In [12]:
pattern = r"\[\d{1,2}/\d{1,2}/\d{2,4},\s*\d{1,2}:\d{2}:\d{2}\s*[AP]M\]"

In [14]:
messages = re.split(pattern, data)[1:]  
messages

[' abhay: \u200eMessages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them.\n',
 ' abhay: .\n',
 ' Abhishek jha_20233504: https://www.instagram.com/reel/Cv_67H3otmN/?igshid=MzRlODBiNWFlZA==\n\u200e',
 ' abhay: \u200evideo omitted\n',
 ' abhay: Abey hostel me light aa rahi hai kya\n',
 ' Abhishek jha_20233504: yes bro\n',
 ' abhay: \u200eThis message was deleted.\n',
 ' Abhishek jha_20233504: bro\n',
 ' Abhishek jha_20233504: turn on the hotspot \U0001f979\n',
 ' Abhishek jha_20233504: for me\n',
 ' Abhishek jha_20233504: Axa khula huwa hi hain\n',
 ' abhay: https://colab.research.google.com/drive/1NDBWpKLM9CV18h2bLyQjnjSLIq0acTGt\n',
 ' abhay: https://colab.research.google.com/drive/1GOqgrB7GVGwEEAzt40vZG-mY2yTe8cCS?usp=sharing\n',
 ' abhay: \u200eMissed voice call\n\u200e',
 ' abhay: CSED-1(Computer programing)-20230823T044424Z-001.zip \u200edocument omitted\n',
 ' abhay: isme notes me jaana\n',
 ' abhay: scope of a variable\n\ncall by value call by address\n\nwhat is loop\n\nwhile loop and for loop what is advantage of switch over if else what is the use of conditional operators int and float (2 to the power till 16) what is the use of break first 15 questions from (chapter 2,3,4,5) (outputs)\n\nclasswork questions what is recursion?\n',
 ' Abhishek jha_20233504: scope of a variable\ncall by value call by address what is loop\nwhile loop and for loop\nwhat is advantage of switch over if else what is the use of conditional operators int and float (2 to the power till 16)\nwhat is the use of break\n\u200e',
 ' abhay: \u200eimage omitted\n\u200e',
 ' abhay: \u200eimage omitted\n\u200e',
 ' abhay: \u200eimage omitted\n\u200e',
 ' abhay: \u200eimage omitted\n\u200e',
 ' abhay: calculus maths20231003 20.5.00.pdf • \u200e21 pages \u200edocument omitted\n\u200e',
 ' abhay: \u200eimage omitted\n',
 ' Abhishek jha_20233504: bhai\n',
 ' Abhishek jha_20233504: kuch khane chale\n',
 ' Abhishek jha_20233504: \U0001f979\n',
 ' abhay: So jaa\n',
 ' Abhishek jha_20233504: zimzam\n',
 ' Abhishek jha_20233504: \U0001f979\n',
 ' abhay: Bhai neend aa raha\n',
 ' Abhishek jha_20233504: 2 min lagega\n',
 ' abhay: So jaa\n',
 ' abhay: Fir neend toot jaayega\n',
 ' Abhishek jha_20233504: chapal bhi tere room meh hain\n',
 ' Abhishek jha_20233504: bhai\n',
 ' Abhishek jha_20233504: sunnaa\n\u200e',
 ' abhay: \u200eimage omitted\n\u200e',
 ' abhay: Here are my UPI details\nName - Abhay Sachan  So  Rajiv Kumar Sachan\nUPI Handle - 918318656396@paytm \u200eimage omitted\n',
 ' Abhishek jha_20233504: bhai\n',
 ' Abhishek jha_20233504: ish period ka attendce kardena\n',
 ' Abhishek jha_20233504: plz\n',
 ' Abhishek jha_20233504: next class meh atta hoon\n',
 ' abhay: Ok\n',
 ' Abhishek jha_20233504: xorde,ek dusre ko kehdiya hain\n',
 ' abhay: Ok\n\u200e',
 ' Abhishek jha_20233504: binarySearch.c \u200edocument omitted\n\u200e',
 ' Abhishek jha_20233504: bubble.c \u200edocument omitted\n\u200e',
 ' Abhishek jha_20233504: bubble2.c \u200edocument omitted\n\u200e',
 ' Abhishek jha_20233504: InsertionSort.c \u200edocument omitted\n\u200e',
 ' Abhishek jha_20233504: minmax.c \u200edocument omitted\n\u200e',
 ' Abhishek jha_20233504: output.pdf • \u200e8 pages \u200edocument omitted\n\u200e',
 ' Abhishek jha_20233504: reverse1.c \u200edocument omitted\n\u200e',
 ' Abhishek jha_20233504: reverse2.c \u200edocument omitted\n\u200e',
 ' Abhishek jha_20233504: sectionsort.c \u200edocument omitted\n',
 ' Abhishek jha_20233504: payment hogya bhai\n',
 ' Abhishek jha_20233504: id:abhishek16\npassword:Abhishek16@\n',
 ' Abhishek jha_20233504: bhai sunna\n',
 ' abhay: Bol\n',
 ' Abhishek jha_20233504: 50 pay kardega bhai,khula nahi hain,Tujhe meh bhaiya se karadunga apne khate ka pay\U0001f979\n\u200e',
 ' Abhishek jha_20233504: \u200eimage omitted\n',
 ' Abhishek jha_20233504: ye dokan wala 500 ka khula nahi kar rha\n',
 ' Abhishek jha_20233504: Raste meh hoon\n',
 ' abhay: Ruk acha\n',
 ' Abhishek jha_20233504: hogya?\n',
 ' abhay: 2 min lagega\n',
 ' Abhishek jha_20233504: abe\n',
 ' Abhishek jha_20233504: bus nikalne wala hain\n',
 ' Abhishek jha_20233504: haldi\n',
 ' Abhishek jha_20233504: jaldi\n',
 ' abhay: Shyamu naam hai\n',
 ' Abhishek jha_20233504: ha\n',
 ' Abhishek jha_20233504: bhai\n',
 ' abhay: Pooch\n',
 ' abhay: Ho raha\n',
 ' Abhishek jha_20233504: huwa?\n',
 ' abhay: Abe class me net nhii chal raha processing me hai\n',
 ' abhay: Ho gaya\n',
 ' Abhishek jha_20233504: 😍😍😍😍\n',
 ' Abhishek jha_20233504: bhai\n',
 ' Abhishek jha_20233504: assignment?\n',
 ' abhay: Kar diya hai week 5 ka\n',
 ' abhay: Abhi week 6 ka\n',
 ' Abhishek jha_20233504: Thankyou bhai\U0001f979\U0001f979\U0001f979\n',
 ' abhay: Tera week 6 bhi kar diya\n',
 ' Abhishek jha_20233504: \U0001f979\U0001f979\U0001f979\U0001f979\n',
 ' abhay: Week 5 me teri output reh gayi thu\n',
 ' abhay: Usko baad me Kari thi\n',
 ' Abhishek jha_20233504: ye le chuma😘\n\u200e',
 ' abhay: \u200esticker omitted\n',
 ' abhay: Kaha hai tu abhi\n',
 ' Abhishek jha_20233504: pata nahi bhai bas chale ja rahe hain\n',
 ' abhay: 😂😂\n',
 ' abhay: Chalo subah Tak pahucha degi\n\u200e',
 ' Abhishek jha_20233504: \u200eimage omitted\n',
 ' Abhishek jha_20233504: iska matlab kya hota hain\n',
 ' abhay: 23 ko last date hai assignment submit karne ki\n',
 ' Abhishek jha_20233504: mera toh hogya haina,\n',
 ' abhay: AIML wala hai ye\n',
 ' Abhishek jha_20233504: bhai woh bhi karde\U0001f979,Gau pe hoon\n',
 ' abhay: https://colab.research.google.com/drive/1SX819z-zcUd3e4FklSmYW1GjVQMSS001#scrollTo=ML3mP28lKQpv\n',
 ' abhay: Isme. Name change karde\n',
 ' abhay: Thoda edit karde\n',
 ' abhay: Upload karde classroom.me\n',
 ' Abhishek jha_20233504: areh mere pass laptop bhi nahi hain abhi,Gau pe hoon,30 mb pe chala rha hoon\n',
 ' Abhishek jha_20233504: \U0001f979\n',
 ' abhay: Abe to Google classroom ke liye account chaiye\n',
 ' abhay: Abhishek pachlaniya se bol de\n',
 ' Abhishek jha_20233504: Thik hain bro\n',
 ' abhay: Uske me Tera login hai\n',
 ' Abhishek jha_20233504: paper suna diya?\n',
 ' Abhishek jha_20233504: ethics ka?\n',
 ' abhay: Haa\n',
 ' abhay: But tera dekh nhii paaya\n',
 ' Abhishek jha_20233504: mera attendence lagaya?\n',
 ' abhay: Bahut kam bache the\n',
 ' abhay: Naa\n',
 ' Abhishek jha_20233504: chutiya\n',
 ' Abhishek jha_20233504: kamina\n',
 ' abhay: Bache hi nhii the saale\n',
 ' abhay: Start ke 20 me bas 3 bache the\n',
 ' abhay: Poore A1 me 14 bache aaye the\n',
 ' Abhishek jha_20233504: 1 nov ko aaunga,Aab direct november se padhai suru😂\n',
 ' Abhishek jha_20233504: Axa axa\n',
 ' Abhishek jha_20233504: roj ka 6 6 ghante padhenge\n',
 ' abhay: Bilkul ab se ekdum serious 😂🤣\n',
 ' Abhishek jha_20233504: pura november achese padhlenge fhir december me mast se exam sab denge aur winter holiday khusi. khusi manayenge\n',
 ' Abhishek jha_20233504: plan fixed\n\u200e',
 ' abhay: \u200esticker omitted\n',
 ' Abhishek jha_20233504: You also join okay brother,dono sath me 9 cgpa layenge\n',
 ' Abhishek jha_20233504: 🤝\n',
 ' Abhishek jha_20233504: aag laga denge aag\n\u200e',
 ' abhay: \u200esticker omitted\n',
 ' Abhishek jha_20233504: ha yese hi😂\n\u200e',
 ' abhay: \u200esticker omitted\n\u200e',
 ' abhay: \u200evideo omitted\n\u200e',
 ' abhay: \u200eimage omitted\n\u200e',
 ' abhay: \u200evideo omitted\n\u200e',
 ' abhay: \u200evideo omitted\n\u200e',
 ' abhay: \u200evideo omitted\n\u200e',
 ' abhay: \u200eimage omitted\n',
 ' Abhishek jha_20233504: https://drive.google.com/file/d/1EeTid4Sn9QeicbvrykI16KABDYigmH1e/view?usp=drivesdk\n\u200e',
 ' abhay: integral calculus.pdf • \u200e14 pages \u200edocument omitted\n\u200e',
 ' abhay: maths20230911 16.31.38.pdf • \u200e34 pages \u200edocument omitted\n\u200e',
 ' abhay: DOC-20231003-WA0015. • \u200e21 pages \u200edocument omitted\n\u200e',
 ' Abhishek jha_20233504: \u200eimage omitted\n\u200e',
 ' Abhishek jha_20233504: \u200eimage omitted\n\u200e',
 ' Abhishek jha_20233504: \u200eimage omitted\n\u200e',
 ' Abhishek jha_20233504: \u200eimage omitted\n',
 ' Abhishek jha_20233504: \u200eVoice call, \u200e10 sec\n\u200e',
 ' Abhishek jha_20233504: \u200eimage omitted\n',
 ' Abhishek jha_20233504: jaldi\n',
 ' Abhishek jha_20233504: jaldi\n',
 ' abhay: Done\n\u200e',
 ' abhay: Paid on Paytm. Check your payment history here:\nhttps://m.paytm.me/passbook_landing \u200eimage omitted\n',
 ' abhay: Abhay sachan 20233008\n',
 ' abhay: Abhishek 20233013\n',
 ' abhay: No dikha raha  kya\n',
 ' abhay: Ye bata\n',
 ' Abhishek jha_20233504: nahi bhai\n',
 ' abhay: Akshai bala 20233507\n\u200e',
 ' Abhishek jha_20233504: \u200eimage omitted\n',
 ' Abhishek jha_20233504: bro isko 50 karde\n',
 ' abhay: kar diye\n\u200e',
 ' Abhishek jha_20233504: \u200eimage omitted\n',
 ' Abhishek jha_20233504: isko 40 karde,Aaj 500 hojayega,room pe aake direct 500 dedunga\n',
 ' Abhishek jha_20233504: bhai\n',
 ' Abhishek jha_20233504: assignment 3 ka note vhejde jaldi\n',
 ' Abhishek jha_20233504: solution\n',
 ' abhay: Nhii hai mere pass\n',
 ' Abhishek jha_20233504: bhai\n',
 ' Abhishek jha_20233504: bro\n',
 ' Abhishek jha_20233504: sunna\n',
 ' Abhishek jha_20233504: \u200eVoice call, \u200eNo answer\n',
 ' Abhishek jha_20233504: bhai\n',
 ' abhay: Bol\n',
 ' Abhishek jha_20233504: goyal pe 20 payment karde plz\n',
 ' Abhishek jha_20233504: QR vhejrha hoon\n\u200e',
 ' Abhishek jha_20233504: \u200eimage omitted\n',
 ' Abhishek jha_20233504: jaldi\n',
 ' abhay: Ok\n',
 ' Abhishek jha_20233504: hogya?\n',
 ' Abhishek jha_20233504: done?\n',
 ' Abhishek jha_20233504: huwa?\n',
 ' Abhishek jha_20233504: jaldi karna\n',
 ' Abhishek jha_20233504: sale\n',
 ' abhay: ho gya\n\u200e',
 ' abhay: Paid on Paytm. Check your payment history here:\nhttps://m.paytm.me/passbook_landing \u200eimage omitted\n',
 ' abhay: https://www.vijaysales.com/hp-victus-gaming-laptop-15-fa0998tx-12th-gen-core-i5-16gb-ram-512-gb-ssd-15-6-inch-39-62-cm-display-4-gb-rtx-graphics-win-11-office/24048\n',
 ' abhay: AI ML ASSIGNMENTS\n\n1-pdf\n2-https://colab.research.google.com/drive/1--4VFFcxVnry0HqgQxXPENYxIJAeIJI8\n3-https://colab.research.google.com/drive/1zpcGp89NyaIF3GSJMcO5_voswi82vANb\n4-https://colab.research.google.com/drive/1CkY9Hkp3CYi429_XahXnMslNI1hgkqsX\n5-https://colab.research.google.com/drive/1SX819z-zcUd3e4FklSmYW1GjVQMSS001\n6-https://colab.research.google.com/drive/1jGeEIfL4DPGR42ht9y5hPD8MYU6L0k_B\n7-https://colab.research.google.com/drive/1ko1PIDGpXcm8HF2JaCxY3X3GSZCvvqTi\n8-https://colab.research.google.com/drive/1-8XFVMQJJTutMPSpV3eJLLGqQQjBLegB\n9-https://colab.research.google.com/drive/1kNpyOJ7ueI9TyuRyYZlQ_o5iQVym0hOE\n10-https://colab.research.google.com/drive/1zRrI_gavWxiygAI5OawtUx4AafnYxKaf\n',
 ' abhay: import pandas as pd\ndic={"days":["monday","tuesday","wednesday","thursday","friday","satarday","sunday"],"rainfall":[]}\nl=eval(input("Enter rainfall in list :"))\ndic["rainfall"]=l\ndf=pd.DataFrame(dic)\nprint(df)\ndf.describe()\n',
 ' Abhishek jha_20233504: \u200eVoice call, \u200eNo answer\n',
 ' Abhishek jha_20233504: sunna\n',
 ' abhay: Bol\n',
 ' Abhishek jha_20233504: math ka ode ka syllabus kya hain\n',
 ' Abhishek jha_20233504: wo vhejdeto\n',
 ' Abhishek jha_20233504: ek dost ko vhejna hain\n',
 ' abhay: Nhii pata\n',
 ' abhay: https://drive.google.com/drive/folders/16tVRfXYVJZbtxcnmCEI8fw_dT48zUx0I\n',
 ' Abhishek jha_20233504: main( )\n§\nstatie int ar 1 = do,12,3,47\nint *xpt= P;\nStatte int *pls- fa, atls ar 2, arsatrz,\nAto ++;\npoint Cuy d y.dled in", ptor p, xptr-a, +* ptr);\n*pfp ++;\nprintf ("-d % d 1.d In", Pts p, aptora; xxptr);\n*++php\nprintf ("\'4 %4 \'%. d in\'", ptr-P, xeptr-a xApte);\n++ *ptp;\nprintf ("%. d%.d/etIn", pto-p, * pto-a, xxptro),;\n',
 ' Abhishek jha_20233504: highest package\n',
 ' abhay: 🥳😂\n',
 ' Abhishek jha_20233504: https://www.amazon.in/Led-Strip-Metalled-Multicolour-Waterproof/dp/B0BD5SYDNT/ref=sr_1_33?crid=3FPMZQWBA6F9P&keywords=rgb%2Bmulti%2Bcolour%2Bled%2Blight&qid=1704612940&sprefix=rgb%2Bmul%2Caps%2C235&sr=8-33&th=1\n',
 ' Abhishek jha_20233504: https://www.amazon.in/Syvo-3130-Aluminum-Universal-Lightweight/dp/B07N42JB4S/ref=sr_1_3?crid=289JQWNX38EBC&keywords=tripod&qid=1704613140&sprefix=tripod%2Caps%2C207&sr=8-3&th=1\n',
 ' Abhishek jha_20233504: https://www.amazon.in/JBL-Commercial-Omnidirectional-Microphone-Conferences/dp/B08SCG35MG/ref=sr_1_7?crid=AGPWQYM7OCEK&keywords=mic&qid=1704613168&sprefix=mic%2Caps%2C217&sr=8-7&th=1\n\u200e',
 ' abhay: \u200eimage omitted\n',
 ' Abhishek jha_20233504: \u200eVoice call, \u200eNo answer\n',
 ' Abhishek jha_20233504: \u200eVoice call, \u200eNo answer\n\u200e',
 ' abhay: \u200eimage omitted\n',
 ' Abhishek jha_20233504: \u200eVoice call, \u200e1 min\n',
 ' Abhishek jha_20233504: NLH1?\n',
 ' abhay: \u200eMissed voice call, \u200eTap to call back\n',
 ' Abhishek jha_20233504: \u200eVoice call, \u200e20 sec\n',
 ' Abhishek jha_20233504: kuch kha lete toh acha hota\n',
 ' Abhishek jha_20233504: \u200eVoice call, \u200e4 sec\n',
 ' Abhishek jha_20233504: \u200eVoice call, \u200eNo answer\n\u200e',
 ' Abhishek jha_20233504: \u200eimage omitted\n',
 ' Abhishek jha_20233504: 120 karde\n\u200e',
 ' Abhishek jha_20233504: \u200eimage omitted\n',
 ' Abhishek jha_20233504: \u200eVoice call, \u200e16 sec\n',
 ' Abhishek jha_20233504: Quick\n',
 ' abhay: Done\n',
 ' Abhishek jha_20233504: Thanks bro\n',
 ' Abhishek jha_20233504: love you\n',
 ' abhay: \u200eThis message was deleted.\n',
 ' abhay: Apne Gharwalo ko call karle phone aaya tha unka\n',
 ' abhay: 5,6, and 16-19\n',
 ' abhay: Itne karne hai tujhe\n\u200e',
 ' abhay: \u200eimage omitted\n',
 ' Abhishek jha_20233504: \u200eYou deleted this message.\n',
 ' Abhishek jha_20233504: \u200eYou deleted this message.\n',
 ' Abhishek jha_20233504: \u200eYou deleted this message.\n\u200e',
 ' abhay: Abhishek kumar jha.pdf • \u200e39 pages \u200edocument omitted\n',
 ' abhay: sun\n',
 ' Abhishek jha_20233504: sunna\n',
 ' abhay: jo tune DS ka assignment bheja hai\n',
 ' abhay: wo bhi copy me karke submit karna hai\n',
 ' abhay: aur agar yahi bc chalti rahi to mai copy me karunga\n',
 ' abhay: file me nhii\n',
 ' Abhishek jha_20233504: kya?\n',
 ' Abhishek jha_20233504: okay bro\n',
 ' abhay: abe pooch raha hu\n\u200e',
 ' abhay: Assignment-2.pdf • \u200e1 page \u200edocument omitted\n',
 ' abhay: ye wala\n',
 ' abhay: sir ne kuch bola hai\n',
 ' abhay: handwritten wali bc\n',
 ' abhay: ye bkl jaha dikh jaata hai gussa hi aata hai mereko\n',
 ' Abhishek jha_20233504: Aayein?\n',
 ' abhay: \u200eVoice call, \u200e12 sec\n',
 ' Abhishek jha_20233504: \u200eVoice call, \u200e54 sec\n',
 ' abhay: Saale agar seniors ho to mat khulwana gate\n',
 ' abhay: saale kidhar hai\n',
 ' abhay: mera phone leke gaya hai\n',
 ' abhay: aur mere earpods bhi\n',
 ' abhay: pitega tu merese😠\n',
 ' Abhishek jha_20233504: 😘😘\n',
 ' abhay: 😖😖\n',
 ' abhay: bhai padhai karni hai\n',
 ' abhay: Oii\n',
 ' Abhishek jha_20233504: habbhai\n',
 ' abhay: Tera proxy lagana hai?\n',
 ' Abhishek jha_20233504: ha bhai\n',
 ' abhay: 🥺🥺\n',
 ' Abhishek jha_20233504: jaroori hain\n',
 ' abhay: Dekhte hai\n',
 ' Abhishek jha_20233504: bohot din badh kaha hoon\n',
 ' Abhishek jha_20233504: mene\n',
 ' Abhishek jha_20233504: karde\n',
 ' abhay: . \u200e<This message was edited>\n',
 ' abhay: Thik hai laga dega 🥲🥲\n',
 ' Abhishek jha_20233504: Ajana\n',
 ' Abhishek jha_20233504: Jaldi!\n',
 ' Abhishek jha_20233504: 6:00 pm tak\n',
 ' abhay: Class me hu abhi\n',
 ' abhay: Waha hai kya\n',
 ' abhay: Aur start kab hoga\n\u200e',
 ' abhay: ds assignment.pdf • \u200e10 pages \u200edocument omitted\n',
 ' Abhishek jha_20233504: \u200eVoice call, \u200eNo answer\n',
 ' Abhishek jha_20233504: aaj seminar hall ajana\n',
 ' abhay: Try\n',
 ' Abhishek jha_20233504: areh ajana\n',
 ' Abhishek jha_20233504: briefing lite lo\n',
 ' Abhishek jha_20233504: 15,20 min me aja\n',
 ' abhay: abe 7 baje hai na\n',
 ' Abhishek jha_20233504: usko lite lo\n',
 ' abhay: aur man to nhii hai mera\n',
 ' abhay: acha\n',
 ' Abhishek jha_20233504: Ajao\n',
 ' abhay: seminar hall me kya hi karwayenge\n',
 ' Abhishek jha_20233504: idhar refreshment bhi hain\n',
 ' abhay: refreshment ka lalach diya jaa raha\n',
 ' abhay: 🤣🤣\n',
 ' Abhishek jha_20233504: aur me apne taraf 2 extra dunga\n',
 ' abhay: acha\n',
 ' Abhishek jha_20233504: areh aja bhai,Aaj Tseries ke filmmaker aarahe hain\n',
 ' Abhishek jha_20233504: aja\n',
 ' Abhishek jha_20233504: tuh aur abhay jha\n',
 ' abhay: 🤣🤣\n',
 ' Abhishek jha_20233504: Jaldi\n',
 ' abhay: chal acha\n',
 ' Abhishek jha_20233504: Jaldi bhai\n',
 ' Abhishek jha_20233504: abhay jha ko bhi le ana\n',
 ' abhay: ok\n',
 ' Abhishek jha_20233504: bhai aaj ahijana\n',
 ' Abhishek jha_20233504: tujhe meri kasam hain\n',
 ' abhay: Mujhe khane ko acha khasa chaiye\n',
 ' abhay: Warna tu dekhiyo\n',
 ' Abhishek jha_20233504: main alag de dunga\n',
 ' Abhishek jha_20233504: pakka\n',
 ' Abhishek jha_20233504: aja aaj\n',
 ' Abhishek jha_20233504: jaldi\n',
 ' abhay: Ok\n',
 ' abhay: Aata hu\n',
 ' Abhishek jha_20233504: jha ko\n',
 ' abhay: 10 mib\n',
 ' abhay: Min\n',
 ' Abhishek jha_20233504: thik hain\n',
 ' Abhishek jha_20233504: \u200eVoice call, \u200eNo answer\n',
 ' Abhishek jha_20233504: aja bhai\n',
 ' Abhishek jha_20233504: \u200eVoice call, \u200eNo answer\n',
 ' Abhishek jha_20233504: \u200eVoice call, \u200eNo answer\n',
 ' Abhishek jha_20233504: bhai ajana\n',
 ' Abhishek jha_20233504: \u200eVoice call, \u200eNo answer\n',
 ' abhay: Aa raha\n',
 ' abhay: Bas\n',
 ' abhay: Jha ko.lelu\n',
 ' Abhishek jha_20233504: bhai meh rone lagunga\n',
 ' Abhishek jha_20233504: aaja\n',
 ' abhay: 🤣🤣\n',
 ' abhay: Abe jha ko bula.lu niche\n',
 ' abhay: Mai niche hi hu\n',
 ' Abhishek jha_20233504: okay\n',
 ' abhay: Wo so.raha tha\n',
 ' abhay: To uthaya usko\n',
 ' Abhishek jha_20233504: Jaldi\n',
 ' abhay: On the way\n',
 ' abhay: 🤧\n',
 ' abhay: Saale kitna jaayega\n',
 ' abhay: 2 ghanta barbaad ho gaya\n',
 ' abhay: 🥲\n',
 ' Abhishek jha_20233504: suna\n',
 ' Abhishek jha_20233504: Apna QR vhejto\n',
 ' Abhishek jha_20233504: 500 vhejta hoon abhii\n\u200e',
 ' abhay: \u200eimage omitted\n',
 ' abhay: Sujeet\n+917572080484\nhttps://truecaller.com/search/in/+917572080484\n\nsent using Truecaller\n',
 ' abhay: 1) Sustainable Development Goal(water, air, soil).\n2)Environmental laws & acts\n',
 ' Abhishek jha_20233504: The Sustainable Development Goals (SDGs) are a set of 17 global objectives established by the United Nations in 2015 to address a wide range of social, economic, and environmental challenges. These goals are designed to promote sustainable development and improve the well-being of people worldwide by 2030. The SDGs cover a broad spectrum of issues, including poverty, hunger, health, education, gender equality, clean water, sanitation, affordable and clean energy, decent work and economic growth, industry innovation, reduced inequalities, sustainable cities, responsible consumption, climate action, life below water, life on land, peace, justice, and strong institutions.\n\nEach goal consists of specific targets and indicators to measure progress. The SDGs recognize the interconnectedness of global challenges and emphasize the need for collaborative efforts among governments, businesses, civil society, and individuals to achieve meaningful and lasting impact. The goals also prioritize leaving no one behind, aiming to address disparities and ensure that the benefits of development reach all segments of society.\n\nThe SDGs provide a universal framework that guides countries and stakeholders in formulating policies, strategies, and actions to address pressing issues and create a more equitable, sustainable, and resilient world. As a comprehensive agenda, the SDGs inspire collective action towards a shared vision of a better future for people and the planet.\n\u200e',
 ' Abhishek jha_20233504: Optical Data Storage Video.pptx \u200edocument omitted\n\u200e',

In [15]:
dates = re.findall(pattern, data)
dates

['[19/08/23, 7:53:34\u202fPM]',
 '[19/08/23, 7:53:34\u202fPM]',
 '[19/08/23, 7:53:39\u202fPM]',
 '[19/08/23, 7:55:03\u202fPM]',
 '[22/08/23, 5:26:00\u202fPM]',
 '[22/08/23, 5:50:34\u202fPM]',
 '[22/08/23, 5:57:51\u202fPM]',
 '[28/08/23, 10:32:50\u202fPM]',
 '[28/08/23, 10:33:00\u202fPM]',
 '[28/08/23, 10:33:03\u202fPM]',
 '[28/08/23, 10:33:18\u202fPM]',
 '[10/09/23, 2:32:21\u202fPM]',
 '[17/09/23, 11:48:27\u202fPM]',
 '[21/09/23, 7:17:45\u202fPM]',
 '[26/09/23, 4:38:45\u202fPM]',
 '[26/09/23, 4:38:52\u202fPM]',
 '[26/09/23, 11:15:58\u202fPM]',
 '[26/09/23, 11:16:00\u202fPM]',
 '[26/09/23, 11:28:47\u202fPM]',
 '[26/09/23, 11:28:58\u202fPM]',
 '[26/09/23, 11:29:10\u202fPM]',
 '[26/09/23, 11:40:53\u202fPM]',
 '[03/10/23, 8:05:26\u202fPM]',
 '[05/10/23, 9:31:02\u202fPM]',
 '[11/10/23, 12:32:47\u202fAM]',
 '[11/10/23, 12:32:51\u202fAM]',
 '[11/10/23, 12:32:58\u202fAM]',
 '[11/10/23, 12:33:04\u202fAM]',
 '[11/10/23, 12:33:11\u202fAM]',
 '[11/10/23, 12:33:22\u202fAM]',
 '[11/10/23, 12:33:22\u202fAM]',
 '[11/10/23, 12:33:28\u202fAM]',
 '[11/10/23, 12:33:40\u202fAM]',
 '[11/10/23, 12:33:52\u202fAM]',
 '[11/10/23, 12:34:13\u202fAM]',
 '[14/10/23, 9:45:43\u202fAM]',
 '[14/10/23, 9:45:44\u202fAM]',
 '[14/10/23, 10:10:22\u202fAM]',
 '[15/10/23, 4:04:22\u202fPM]',
 '[17/10/23, 2:10:06\u202fPM]',
 '[17/10/23, 2:10:21\u202fPM]',
 '[17/10/23, 2:10:22\u202fPM]',
 '[17/10/23, 2:10:29\u202fPM]',
 '[17/10/23, 2:12:43\u202fPM]',
 '[17/10/23, 2:13:20\u202fPM]',
 '[17/10/23, 2:13:27\u202fPM]',
 '[18/10/23, 7:23:08\u202fPM]',
 '[18/10/23, 7:23:08\u202fPM]',
 '[18/10/23, 7:23:08\u202fPM]',
 '[18/10/23, 7:23:08\u202fPM]',
 '[18/10/23, 7:23:08\u202fPM]',
 '[18/10/23, 7:23:09\u202fPM]',
 '[18/10/23, 7:23:09\u202fPM]',
 '[18/10/23, 7:23:09\u202fPM]',
 '[18/10/23, 7:23:09\u202fPM]',
 '[18/10/23, 11:43:17\u202fPM]',
 '[19/10/23, 8:09:38\u202fAM]',
 '[19/10/23, 10:26:03\u202fAM]',
 '[19/10/23, 10:26:50\u202fAM]',
 '[19/10/23, 10:27:23\u202fAM]',
 '[19/10/23, 10:27:29\u202fAM]',
 '[19/10/23, 10:27:46\u202fAM]',
 '[19/10/23, 10:27:54\u202fAM]',
 '[19/10/23, 10:28:02\u202fAM]',
 '[19/10/23, 10:28:19\u202fAM]',
 '[19/10/23, 10:28:35\u202fAM]',
 '[19/10/23, 10:28:41\u202fAM]',
 '[19/10/23, 10:28:44\u202fAM]',
 '[19/10/23, 10:28:47\u202fAM]',
 '[19/10/23, 10:28:53\u202fAM]',
 '[19/10/23, 10:29:23\u202fAM]',
 '[19/10/23, 10:29:34\u202fAM]',
 '[19/10/23, 10:29:39\u202fAM]',
 '[19/10/23, 10:29:59\u202fAM]',
 '[19/10/23, 10:30:12\u202fAM]',
 '[19/10/23, 10:30:41\u202fAM]',
 '[19/10/23, 10:31:00\u202fAM]',
 '[19/10/23, 10:31:13\u202fAM]',
 '[19/10/23, 10:38:47\u202fAM]',
 '[19/10/23, 10:06:26\u202fPM]',
 '[19/10/23, 10:07:14\u202fPM]',
 '[19/10/23, 10:08:40\u202fPM]',
 '[19/10/23, 10:08:45\u202fPM]',
 '[19/10/23, 10:08:59\u202fPM]',
 '[19/10/23, 10:32:48\u202fPM]',
 '[19/10/23, 10:36:06\u202fPM]',
 '[19/10/23, 10:36:34\u202fPM]',
 '[19/10/23, 10:36:40\u202fPM]',
 '[19/10/23, 10:36:53\u202fPM]',
 '[19/10/23, 10:37:00\u202fPM]',
 '[19/10/23, 10:37:31\u202fPM]',
 '[19/10/23, 10:37:53\u202fPM]',
 '[19/10/23, 10:38:06\u202fPM]',
 '[19/10/23, 10:38:25\u202fPM]',
 '[22/10/23, 6:37:04\u202fAM]',
 '[22/10/23, 6:37:11\u202fAM]',
 '[22/10/23, 9:08:17\u202fAM]',
 '[22/10/23, 9:18:20\u202fAM]',
 '[22/10/23, 9:21:58\u202fAM]',
 '[22/10/23, 9:22:22\u202fAM]',
 '[22/10/23, 9:22:47\u202fAM]',
 '[22/10/23, 9:22:57\u202fAM]',
 '[22/10/23, 9:23:01\u202fAM]',
 '[22/10/23, 9:23:08\u202fAM]',
 '[22/10/23, 9:23:28\u202fAM]',
 '[22/10/23, 9:23:37\u202fAM]',
 '[22/10/23, 9:24:19\u202fAM]',
 '[22/10/23, 9:24:35\u202fAM]',
 '[22/10/23, 9:24:42\u202fAM]',
 '[22/10/23, 9:24:45\u202fAM]',
 '[30/10/23, 12:01:42\u202fPM]',
 '[30/10/23, 12:01:45\u202fPM]',
 '[30/10/23, 12:07:17\u202fPM]',
 '[30/10/23, 12:07:28\u202fPM]',
 '[30/10/23, 12:07:31\u202fPM]',
 '[30/10/23, 12:07:36\u202fPM]',
 '[30/10/23, 12:07:38\u202fPM]',
 '[30/10/23, 12:07:41\u202fPM]',
 '[30/10/23, 12:07:44\u202fPM]',
 '[30/10/23, 12:07:47\u202fPM]',
 '[30/10/23, 12:08:05\u202fPM]',
 '[30/10/23, 12:08:26\u202fPM]',
 '[30/10/23, 12:08:29\u202fPM]',
 '[30/10/23, 12:08:33\u202fPM]',
 '[30/10/23, 12:08:46\u202fPM]',
 '[30/10/23, 12:09:04\u202fPM]',
 '[30/10/23, 12:09:29\u202fPM]',
 '[30/10/23, 12:09:32\u202fPM]',
 '[30/10/23, 12:09:43\u202fPM]',
 '[30/10/23, 12:10:05\u202fPM]',
 '[30/10/23, 12:10:10\u202fPM]',
 '[30/10/23, 12:10:15\u202fPM]',
 '[30/10/23, 12:10:49\u202fPM]',
 '[30/10/23, 12:11:05\u202fPM]',
 '[30/10/23, 12:11:12\u202fPM]',
 '[01/11/23, 9:04:47\u202fPM]',
 '[01/11/23, 9:04:47\u202fPM]',
 '[01/11/23, 9:05:10\u202fPM]',
 '[01/11/23, 9:05:19\u202fPM]',
 '[01/11/23, 9:08:36\u202fPM]',
 '[07/11/23, 6:23:45\u202fPM]',
 '[08/11/23, 8:53:17\u202fPM]',
 '[16/11/23, 9:23:19\u202fAM]',
 '[16/11/23, 9:31:01\u202fAM]',
 '[16/11/23, 9:34:27\u202fAM]',
 '[18/11/23, 1:23:50\u202fPM]',
 '[18/11/23, 1:29:24\u202fPM]',
 '[18/11/23, 1:29:27\u202fPM]',
 '[18/11/23, 1:29:33\u202fPM]',
 '[23/11/23, 9:56:45\u202fAM]',
 '[23/11/23, 9:57:18\u202fAM]',
 '[23/11/23, 9:57:28\u202fAM]',
 '[23/11/23, 9:57:54\u202fAM]',
 '[23/11/23, 9:58:06\u202fAM]',
 '[23/11/23, 9:58:43\u202fAM]',
 '[24/11/23, 5:00:48\u202fPM]',
 '[24/11/23, 5:00:57\u202fPM]',
 '[24/11/23, 5:16:51\u202fPM]',
 '[24/11/23, 5:16:55\u202fPM]',
 '[24/11/23, 5:17:06\u202fPM]',
 '[24/11/23, 5:17:08\u202fPM]',
 '[25/11/23, 9:02:05\u202fPM]',
 '[25/11/23, 9:02:15\u202fPM]',
 '[25/11/23, 9:03:24\u202fPM]',
 '[26/11/23, 9:03:18\u202fPM]',
 '[26/11/23, 9:03:18\u202fPM]',
 '[28/11/23, 5:47:07\u202fPM]',
 '[28/11/23, 5:47:23\u202fPM]',
 '[28/11/23, 5:47:26\u202fPM]',
 '[28/11/23, 5:53:38\u202fPM]',
 '[28/11/23, 7:19:31\u202fPM]',
 '[28/11/23, 7:19:59\u202fPM]',
 '[28/11/23, 7:20:14\u202fPM]',
 '[28/11/23, 7:20:21\u202fPM]',
 '[28/11/23, 7:20:35\u202fPM]',
 '[28/11/23, 7:20:37\u202fPM]',
 '[28/11/23, 7:20:46\u202fPM]',
 '[28/11/23, 7:20:51\u202fPM]',
 '[28/11/23, 7:21:05\u202fPM]',
 '[28/11/23, 7:21:24\u202fPM]',
 '[28/11/23, 7:21:35\u202fPM]',
 '[28/11/23, 7:21:41\u202fPM]',
 '[28/11/23, 7:22:01\u202fPM]',
 '[28/11/23, 7:22:07\u202fPM]',
 '[28/11/23, 7:22:20\u202fPM]',
 '[28/11/23, 7:22:21\u202fPM]',
 '[28/11/23, 7:22:51\u202fPM]',
 '[28/11/23, 7:23:02\u202fPM]',
 '[28/11/23, 10:19:33\u202fPM]',
 '[03/12/23, 10:24:11\u202fPM]',
 '[03/12/23, 11:21:28\u202fPM]',
 '[10/12/23, 12:56:18\u202fPM]',
 '[10/12/23, 12:56:28\u202fPM]',
 '[10/12/23, 12:56:32\u202fPM]',
 '[10/12/23, 12:56:36\u202fPM]',
 '[10/12/23, 12:56:41\u202fPM]',
 '[10/12/23, 12:56:44\u202fPM]',
 '[10/12/23, 12:56:47\u202fPM]',
 '[14/12/23, 7:28:59\u202fPM]',
 '[15/12/23, 3:37:52\u202fPM]',
 '[26/12/23, 3:29:04\u202fPM]',
 '[26/12/23, 3:31:10\u202fPM]',
 '[07/01/24, 1:08:01\u202fPM]',
 '[07/01/24, 1:09:22\u202fPM]',
 '[07/01/24, 1:14:01\u202fPM]',
 '[11/01/24, 12:02:30\u202fPM]',
 '[11/01/24, 10:52:14\u202fPM]',
 '[11/01/24, 11:46:38\u202fPM]',
 '[17/01/24, 10:41:21\u202fPM]',
 '[18/01/24, 3:41:51\u202fPM]',
 '[18/01/24, 3:43:12\u202fPM]',
 '[19/01/24, 10:29:14\u202fAM]',
 '[23/01/24, 11:56:01\u202fPM]',
 '[23/01/24, 11:56:46\u202fPM]',
 '[24/01/24, 8:50:47\u202fAM]',
 '[25/01/24, 1:03:34\u202fPM]',
 '[30/01/24, 8:03:08\u202fPM]',
 '[30/01/24, 8:03:12\u202fPM]',
 '[30/01/24, 8:03:20\u202fPM]',
 '[30/01/24, 8:03:25\u202fPM]',
 '[30/01/24, 8:04:12\u202fPM]',
 '[30/01/24, 8:05:19\u202fPM]',
 '[30/01/24, 8:10:57\u202fPM]',
 '[30/01/24, 8:10:59\u202fPM]',
 '[30/01/24, 8:22:35\u202fPM]',
 '[02/02/24, 7:51:03\u202fPM]',
 '[06/02/24, 6:13:07\u202fPM]',
 '[06/02/24, 6:13:13\u202fPM]',
 '[10/02/24, 4:56:20\u202fPM]',
 '[10/02/24, 6:53:30\u202fPM]',
 '[10/02/24, 6:53:36\u202fPM]',
 '[10/02/24, 6:53:41\u202fPM]',
 '[11/02/24, 11:47:20\u202fPM]',
 '[13/02/24, 11:30:49\u202fPM]',
 '[13/02/24, 11:30:54\u202fPM]',
 '[13/02/24, 11:31:00\u202fPM]',
 '[13/02/24, 11:31:11\u202fPM]',
 '[13/02/24, 11:31:30\u202fPM]',
 '[13/02/24, 11:31:33\u202fPM]',
 '[13/02/24, 11:32:03\u202fPM]',
 '[13/02/24, 11:32:25\u202fPM]',
 '[13/02/24, 11:32:35\u202fPM]',
 '[13/02/24, 11:32:54\u202fPM]',
 '[13/02/24, 11:33:14\u202fPM]',
 '[13/02/24, 11:33:20\u202fPM]',
 '[13/02/24, 11:33:27\u202fPM]',
 '[13/02/24, 11:33:42\u202fPM]',
 '[13/02/24, 11:37:20\u202fPM]',
 '[13/02/24, 11:38:32\u202fPM]',
 '[17/02/24, 3:59:48\u202fPM]',
 '[17/02/24, 4:26:37\u202fPM]',
 '[17/02/24, 9:30:24\u202fPM]',
 '[17/02/24, 9:30:34\u202fPM]',
 '[17/02/24, 9:30:41\u202fPM]',
 '[17/02/24, 9:30:53\u202fPM]',
 '[17/02/24, 9:35:09\u202fPM]',
 '[17/02/24, 9:35:42\u202fPM]',
 '[17/02/24, 9:35:53\u202fPM]',
 '[19/02/24, 10:25:01\u202fAM]',
 '[19/02/24, 10:25:18\u202fAM]',
 '[19/02/24, 10:25:46\u202fAM]',
 '[19/02/24, 10:25:54\u202fAM]',
 '[19/02/24, 10:25:56\u202fAM]',
 '[19/02/24, 10:26:01\u202fAM]',
 '[19/02/24, 10:26:04\u202fAM]',
 '[19/02/24, 10:26:07\u202fAM]',
 '[19/02/24, 10:26:08\u202fAM]',
 '[19/02/24, 10:26:16\u202fAM]',
 '[19/02/24, 10:26:50\u202fAM]',
 '[19/02/24, 10:27:01\u202fAM]',
 '[19/02/24, 5:48:55\u202fPM]',
 '[19/02/24, 5:48:58\u202fPM]',
 '[19/02/24, 5:49:04\u202fPM]',
 '[19/02/24, 6:03:54\u202fPM]',
 '[19/02/24, 6:19:02\u202fPM]',
 '[19/02/24, 6:19:09\u202fPM]',
 '[19/02/24, 11:42:43\u202fPM]',
 '[20/02/24, 12:31:43\u202fAM]',
 '[20/02/24, 5:43:59\u202fPM]',
 '[20/02/24, 5:49:44\u202fPM]',
 '[20/02/24, 5:56:29\u202fPM]',
 '[20/02/24, 5:56:33\u202fPM]',
 '[20/02/24, 5:56:41\u202fPM]',
 '[20/02/24, 6:09:45\u202fPM]',
 '[20/02/24, 6:09:56\u202fPM]',
 '[20/02/24, 6:10:00\u202fPM]',
 '[20/02/24, 6:10:09\u202fPM]',
 '[20/02/24, 6:10:24\u202fPM]',
 '[20/02/24, 6:10:25\u202fPM]',
 '[20/02/24, 6:10:32\u202fPM]',
 '[20/02/24, 6:10:46\u202fPM]',
 '[20/02/24, 6:10:49\u202fPM]',
 '[20/02/24, 6:10:54\u202fPM]',
 '[20/02/24, 6:11:23\u202fPM]',
 '[20/02/24, 6:11:24\u202fPM]',
 '[20/02/24, 6:11:24\u202fPM]',
 '[20/02/24, 6:11:28\u202fPM]',
 '[20/02/24, 6:11:30\u202fPM]',
 '[20/02/24, 6:11:38\u202fPM]',
 '[20/02/24, 6:11:50\u202fPM]',
 '[20/02/24, 6:11:55\u202fPM]',
 '[20/02/24, 6:12:01\u202fPM]',
 '[20/02/24, 6:12:08\u202fPM]',
 '[20/02/24, 6:13:48\u202fPM]',
 '[20/02/24, 6:13:52\u202fPM]',
 '[20/02/24, 6:14:23\u202fPM]',
 '[20/02/24, 6:14:32\u202fPM]',
 '[20/02/24, 6:14:36\u202fPM]',
 '[20/02/24, 6:14:43\u202fPM]',
 '[20/02/24, 6:14:44\u202fPM]',
 '[20/02/24, 6:14:46\u202fPM]',
 '[20/02/24, 6:14:46\u202fPM]',
 '[20/02/24, 6:14:52\u202fPM]',
 '[20/02/24, 6:14:56\u202fPM]',
 '[20/02/24, 6:14:57\u202fPM]',
 '[20/02/24, 6:14:59\u202fPM]',
 '[20/02/24, 6:15:12\u202fPM]',
 '[20/02/24, 6:29:07\u202fPM]',
 '[20/02/24, 6:30:33\u202fPM]',
 '[20/02/24, 6:30:37\u202fPM]',
 '[20/02/24, 6:33:50\u202fPM]',
 '[20/02/24, 6:33:58\u202fPM]',
 '[20/02/24, 6:34:04\u202fPM]',
 '[20/02/24, 6:34:42\u202fPM]',
 '[20/02/24, 6:34:43\u202fPM]',
 '[20/02/24, 6:34:46\u202fPM]',
 '[20/02/24, 6:34:59\u202fPM]',
 '[20/02/24, 6:35:00\u202fPM]',
 '[20/02/24, 6:35:13\u202fPM]',
 '[20/02/24, 6:35:27\u202fPM]',
 '[20/02/24, 6:35:32\u202fPM]',
 '[20/02/24, 6:35:36\u202fPM]',
 '[20/02/24, 6:35:36\u202fPM]',
 '[20/02/24, 6:35:43\u202fPM]',
 '[20/02/24, 6:36:23\u202fPM]',
 '[20/02/24, 6:37:34\u202fPM]',
 '[20/02/24, 7:48:45\u202fPM]',
 '[20/02/24, 7:48:54\u202fPM]',
 '[20/02/24, 8:18:36\u202fPM]',
 '[20/02/24, 8:18:40\u202fPM]',
 '[20/02/24, 11:38:11\u202fPM]',
 '[20/02/24, 11:38:21\u202fPM]',
 '[20/02/24, 11:38:27\u202fPM]',
 '[21/02/24, 12:51:01\u202fAM]',
 '[21/02/24, 11:24:14\u202fAM]',
 '[25/02/24, 4:28:52\u202fPM]',
 '[25/02/24, 4:52:33\u202fPM]',
 '[26/02/24, 10:03:17\u202fAM]',
 '[26/02/24, 10:03:17\u202fAM]',
 '[26/02/24, 6:02:45\u202fPM]',
 '[27/02/24, 10:56:33\u202fAM]',
 '[27/02/24, 6:47:12\u202fPM]',
 '[29/02/24, 11:38:16\u202fPM]',
 '[01/03/24, 10:49:05\u202fPM]',
 '[02/03/24, 8:46:32\u202fPM]',
 '[02/03/24, 8:46:43\u202fPM]',
 '[09/03/24, 9:42:45\u202fAM]',
 '[10/03/24, 11:06:34\u202fAM]',
 '[16/03/24, 12:32:47\u202fPM]',
 '[16/03/24, 12:32:54\u202fPM]',
 '[16/03/24, 12:33:04\u202fPM]',
 '[17/03/24, 1:31:01\u202fAM]',
 '[17/03/24, 1:21:38\u202fPM]',
 '[21/03/24, 12:54:04\u202fPM]',
 '[21/03/24, 12:54:44\u202fPM]',
 '[21/03/24, 12:55:13\u202fPM]',
 '[21/03/24, 12:55:15\u202fPM]',
 '[21/03/24, 2:52:05\u202fPM]',
 '[21/03/24, 5:07:00\u202fPM]',
 '[21/03/24, 7:02:35\u202fPM]',
 '[21/03/24, 7:04:01\u202fPM]',
 '[21/03/24, 7:04:06\u202fPM]',
 '[21/03/24, 7:07:05\u202fPM]',
 '[25/03/24, 7:36:58\u202fPM]',
 '[25/03/24, 7:37:05\u202fPM]',
 '[25/03/24, 7:37:08\u202fPM]',
 '[25/03/24, 7:39:30\u202fPM]',
 '[26/03/24, 1:16:25\u202fPM]',
 '[26/03/24, 1:31:46\u202fPM]',
 '[26/03/24, 1:31:54\u202fPM]',
 '[26/03/24, 1:37:12\u202fPM]',
 '[27/03/24, 5:06:22\u202fPM]',
 '[27/03/24, 5:06:58\u202fPM]',
 '[27/03/24, 5:07:09\u202fPM]',
 '[27/03/24, 5:07:39\u202fPM]',
 '[27/03/24, 5:07:54\u202fPM]',
 '[27/03/24, 5:08:09\u202fPM]',
 '[27/03/24, 5:08:43\u202fPM]',
 '[27/03/24, 5:08:54\u202fPM]',
 '[27/03/24, 5:09:11\u202fPM]',
 '[27/03/24, 5:09:22\u202fPM]',
 '[27/03/24, 5:09:24\u202fPM]',
 '[27/03/24, 5:10:46\u202fPM]',
 '[27/03/24, 5:10:48\u202fPM]',
 '[27/03/24, 5:11:04\u202fPM]',
 '[27/03/24, 5:15:21\u202fPM]',
 '[28/03/24, 7:21:57\u202fPM]',
 '[28/03/24, 7:22:07\u202fPM]',
 '[28/03/24, 7:24:07\u202fPM]',
 '[28/03/24, 7:24:24\u202fPM]',
 '[28/03/24, 7:24:27\u202fPM]',
 '[28/03/24, 7:24:31\u202fPM]',
 '[28/03/24, 7:24:43\u202fPM]',
 '[28/03/24, 7:24:50\u202fPM]',
 '[28/03/24, 7:25:01\u202fPM]',
 '[28/03/24, 7:25:40\u202fPM]',
 '[28/03/24, 7:25:51\u202fPM]',
 '[28/03/24, 7:26:13\u202fPM]',
 '[28/03/24, 7:26:15\u202fPM]',
 '[28/03/24, 7:26:19\u202fPM]',
 '[28/03/24, 7:28:29\u202fPM]',
 '[28/03/24, 7:28:32\u202fPM]',
 '[28/03/24, 7:28:41\u202fPM]',
 '[28/03/24, 7:28:45\u202fPM]',
 '[28/03/24, 7:30:36\u202fPM]',
 '[28/03/24, 7:30:41\u202fPM]',
 '[28/03/24, 7:35:11\u202fPM]',
 '[28/03/24, 7:35:32\u202fPM]',
 '[28/03/24, 7:37:04\u202fPM]',
 '[28/03/24, 8:59:00\u202fPM]',
 '[28/03/24, 8:59:07\u202fPM]',
 '[28/03/24, 9:00:19\u202fPM]',
 '[28/03/24, 11:41:48\u202fPM]',
 '[28/03/24, 11:41:50\u202fPM]',
 '[28/03/24, 11:42:36\u202fPM]',
 '[28/03/24, 11:43:12\u202fPM]',
 '[31/03/24, 2:58:12\u202fPM]',
 '[31/03/24, 2:58:23\u202fPM]',
 '[31/03/24, 6:29:30\u202fPM]',
 '[31/03/24, 6:29:35\u202fPM]',
 '[31/03/24, 6:30:52\u202fPM]',
 '[31/03/24, 10:13:51\u202fPM]',
 '[31/03/24, 10:13:57\u202fPM]',
 '[31/03/24, 10:14:07\u202fPM]',
 '[31/03/24, 10:14:15\u202fPM]',
 '[31/03/24, 10:15:03\u202fPM]',
 '[31/03/24, 10:15:06\u202fPM]',
 '[31/03/24, 10:15:08\u202fPM]',
 '[31/03/24, 10:15:21\u202fPM]',
 '[31/03/24, 10:15:27\u202fPM]',
 '[31/03/24, 10:15:30\u202fPM]',
 '[31/03/24, 10:15:34\u202fPM]',
 '[31/03/24, 10:15:48\u202fPM]',
 '[31/03/24, 10:15:51\u202fPM]',
 '[31/03/24, 10:15:56\u202fPM]',
 '[31/03/24, 10:15:55\u202fPM]',
 '[31/03/24, 10:16:18\u202fPM]',
 '[03/04/24, 9:49:37\u202fPM]',
 '[03/04/24, 9:50:39\u202fPM]',
 '[03/04/24, 9:50:39\u202fPM]',
 '[03/04/24, 9:50:39\u202fPM]',
 '[03/04/24, 9:50:40\u202fPM]',
 '[03/04/24, 9:50:40\u202fPM]',
 '[04/04/24, 3:27:12\u202fPM]',
 '[09/04/24, 10:30:26\u202fAM]',
 '[09/04/24, 10:39:39\u202fAM]',
 '[09/04/24, 10:45:39\u202fAM]',
 '[09/04/24, 10:45:43\u202fAM]',
 '[09/04/24, 10:45:50\u202fAM]',
 '[09/04/24, 10:45:51\u202fAM]',
 '[09/04/24, 10:45:53\u202fAM]',
 '[09/04/24, 10:46:42\u202fAM]',
 '[09/04/24, 10:46:44\u202fAM]',
 '[11/04/24, 10:39:58\u202fAM]',
 '[14/04/24, 10:02:43\u202fAM]',
 '[14/04/24, 10:03:38\u202fAM]',
 '[14/04/24, 10:05:10\u202fAM]',
 '[14/04/24, 10:05:38\u202fAM]',
 '[14/04/24, 5:17:43\u202fPM]',
 '[14/04/24, 5:18:14\u202fPM]',
 '[14/04/24, 5:18:20\u202fPM]',
 '[15/04/24, 12:42:58\u202fPM]',
 '[15/04/24, 12:44:36\u202fPM]',
 '[16/04/24, 12:19:04\u202fPM]',
 '[16/04/24, 4:59:45\u202fPM]',
 '[16/04/24, 5:06:13\u202fPM]',
 '[20/04/24, 10:07:34\u202fPM]',
 '[24/04/24, 2:06:03\u202fPM]',
 '[25/04/24, 3:07:40\u202fPM]',
 '[25/04/24, 3:13:29\u202fPM]',
 '[25/04/24, 3:14:16\u202fPM]',
 '[25/04/24, 3:14:19\u202fPM]',
 '[25/04/24, 3:14:42\u202fPM]',
 '[25/04/24, 3:14:43\u202fPM]',
 '[25/04/24, 3:14:45\u202fPM]',
 '[25/04/24, 3:14:46\u202fPM]',
 '[25/04/24, 3:14:27\u202fPM]',
 '[25/04/24, 3:16:50\u202fPM]',
 '[25/04/24, 3:17:05\u202fPM]',
 '[25/04/24, 3:17:07\u202fPM]',
 '[25/04/24, 3:17:39\u202fPM]',
 '[25/04/24, 3:18:02\u202fPM]',
 '[25/04/24, 3:18:25\u202fPM]',
 '[25/04/24, 5:31:30\u202fPM]',
 '[25/04/24, 5:31:37\u202fPM]',
 '[27/04/24, 12:08:16\u202fPM]',
 '[30/04/24, 12:16:01\u202fAM]',
 '[30/04/24, 12:16:01\u202fAM]',
 '[30/04/24, 12:16:01\u202fAM]',
 '[30/04/24, 12:16:02\u202fAM]',
 '[01/05/24, 1:23:00\u202fPM]',
 '[02/05/24, 10:52:11\u202fPM]',
 '[02/05/24, 10:52:27\u202fPM]',
 '[03/05/24, 12:26:08\u202fAM]',
 '[03/05/24, 12:26:15\u202fAM]',
 '[04/05/24, 1:26:15\u202fAM]',
 '[04/05/24, 1:26:41\u202fAM]',
 '[06/05/24, 5:14:13\u202fPM]',
 '[06/05/24, 5:16:05\u202fPM]',
 '[06/05/24, 5:16:06\u202fPM]',
 '[06/05/24, 5:16:07\u202fPM]',
 '[06/05/24, 5:17:57\u202fPM]',
 '[06/05/24, 5:18:07\u202fPM]',
 '[06/05/24, 11:16:38\u202fPM]',
 '[07/05/24, 11:10:48\u202fAM]',
 '[07/05/24, 11:11:14\u202fAM]',
 '[07/05/24, 11:11:27\u202fAM]',
 '[07/05/24, 11:11:40\u202fAM]',
 '[07/05/24, 11:12:12\u202fAM]',
 '[07/05/24, 11:12:36\u202fAM]',
 '[07/05/24, 11:13:08\u202fAM]',
 '[07/05/24, 11:13:26\u202fAM]',
 '[07/05/24, 11:13:26\u202fAM]',
 '[07/05/24, 11:13:34\u202fAM]',
 '[07/05/24, 11:13:49\u202fAM]',
 '[07/05/24, 11:14:42\u202fAM]',
 '[07/05/24, 8:28:33\u202fPM]',
 '[07/05/24, 8:29:11\u202fPM]',
 '[09/05/24, 8:21:52\u202fPM]',
 '[09/05/24, 10:30:16\u202fPM]',
 '[17/05/24, 5:03:54\u202fPM]',
 '[17/05/24, 5:04:39\u202fPM]',
 '[17/05/24, 5:04:39\u202fPM]',
 '[17/05/24, 5:04:39\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:04:40\u202fPM]',
 '[17/05/24, 5:05:22\u202fPM]',
 '[17/05/24, 5:05:24\u202fPM]',
 '[18/05/24, 7:39:44\u202fPM]',
 '[18/05/24, 7:40:44\u202fPM]',
 '[19/05/24, 5:06:46\u202fPM]',
 '[19/05/24, 5:06:53\u202fPM]',
 '[19/05/24, 5:07:00\u202fPM]',
 '[19/05/24, 5:07:08\u202fPM]',
 '[21/05/24, 2:26:26\u202fPM]',
 '[21/05/24, 2:27:42\u202fPM]',
 '[21/05/24, 2:27:56\u202fPM]',
 '[21/05/24, 2:28:00\u202fPM]',
 '[21/05/24, 2:28:03\u202fPM]',
 '[21/05/24, 2:28:06\u202fPM]',
 '[21/05/24, 2:28:53\u202fPM]',
 '[21/05/24, 2:29:07\u202fPM]',
 '[21/05/24, 2:29:17\u202fPM]',
 '[22/05/24, 1:54:37\u202fPM]',
 '[22/05/24, 1:54:52\u202fPM]',
 '[22/05/24, 1:54:55\u202fPM]',
 '[22/05/24, 1:55:39\u202fPM]',
 '[22/05/24, 1:55:47\u202fPM]',
 '[22/05/24, 1:55:55\u202fPM]',
 '[22/05/24, 1:56:11\u202fPM]',
 '[22/05/24, 1:57:33\u202fPM]',
 '[22/05/24, 1:58:25\u202fPM]',
 '[23/05/24, 1:47:58\u202fPM]',
 '[23/05/24, 2:10:36\u202fPM]',
 '[23/05/24, 2:12:01\u202fPM]',
 '[25/05/24, 9:46:58\u202fPM]',
 '[25/05/24, 9:47:24\u202fPM]',
 '[27/05/24, 1:49:56\u202fPM]',
 '[28/05/24, 8:52:34\u202fPM]',
 '[28/05/24, 9:56:05\u202fPM]',
 '[28/05/24, 9:56:06\u202fPM]',
 '[28/05/24, 9:56:17\u202fPM]',
 '[28/05/24, 9:56:38\u202fPM]',
 '[28/05/24, 9:56:52\u202fPM]',
 '[28/05/24, 9:57:08\u202fPM]',
 '[28/05/24, 9:57:13\u202fPM]',
 '[28/05/24, 9:57:19\u202fPM]',
 '[03/06/24, 11:54:35\u202fAM]',
 '[04/06/24, 10:23:58\u202fAM]',
 '[04/06/24, 1:52:33\u202fPM]',
 '[04/06/24, 5:17:16\u202fPM]',
 '[04/06/24, 5:19:11\u202fPM]',
 '[04/06/24, 5:19:52\u202fPM]',
 '[04/06/24, 5:20:54\u202fPM]',
 '[04/06/24, 5:21:52\u202fPM]',
 '[04/06/24, 5:22:00\u202fPM]',

In [29]:
df = pd.DataFrame({'date': dates, 'message': messages})
df["date"] = pd.to_datetime(df["date"], format="[%d/%m/%y, %I:%M:%S %p]")

df.head()

                 date                                            message
0 2023-08-19 19:53:34   abhay: ‎Messages and calls are end-to-end enc...
1 2023-08-19 19:53:34                                         abhay: .\n
2 2023-08-19 19:53:39   Abhishek jha_20233504: https://www.instagram....
3 2023-08-19 19:55:03                            abhay: ‎video omitted\n
4 2023-08-22 17:26:00      abhay: Abey hostel me light aa rahi hai kya\n

In [30]:
df.shape

(5697, 2)

In [31]:
 #seperate users and messages
users = []
messages_only = []
for message in df['message']:
    if ": " in message:
        user, msg = message.split(": ", 1)
        users.append(user)
        messages_only.append(msg)
    else:
        users.append("System")
        messages_only.append(message)
df['user'] = users
df['message_only'] = messages_only
df.head()

,date,message,user,message_only
0,2023-08-19 19:53:34,abhay: ‎Messages and calls are end-to-end enc...,abhay,‎Messages and calls are end-to-end encrypted. ...
1,2023-08-19 19:53:34,abhay: .\n,abhay,.\n
2,2023-08-19 19:53:39,Abhishek jha_20233504: https://www.instagram....,Abhishek jha_20233504,https://www.instagram.com/reel/Cv_67H3otmN/?ig...
3,2023-08-19 19:55:03,abhay: ‎video omitted\n,abhay,‎video omitted\n
4,2023-08-22 17:26:00,abhay: Abey hostel me light aa rahi hai kya\n,abhay,Abey hostel me light aa rahi hai kya\n

In [32]:
#delete message column
df = df.drop(columns=['message'])

In [33]:
df.head()

,date,user,message_only
0,2023-08-19 19:53:34,abhay,‎Messages and calls are end-to-end encrypted. ...
1,2023-08-19 19:53:34,abhay,.\n
2,2023-08-19 19:53:39,Abhishek jha_20233504,https://www.instagram.com/reel/Cv_67H3otmN/?ig...
3,2023-08-19 19:55:03,abhay,‎video omitted\n
4,2023-08-22 17:26:00,abhay,Abey hostel me light aa rahi hai kya\n

In [35]:
df['year'] = df['date'].dt.year

In [36]:
df.head()

,date,user,message_only,year
0,2023-08-19 19:53:34,abhay,‎Messages and calls are end-to-end encrypted. ...,2023
1,2023-08-19 19:53:34,abhay,.\n,2023
2,2023-08-19 19:53:39,Abhishek jha_20233504,https://www.instagram.com/reel/Cv_67H3otmN/?ig...,2023
3,2023-08-19 19:55:03,abhay,‎video omitted\n,2023
4,2023-08-22 17:26:00,abhay,Abey hostel me light aa rahi hai kya\n,2023

In [40]:
df['month'] = df['date'].dt.month_name()
df['day'] = df['date'].dt.day
df['hour'] = df['date'].dt.hour
df['minute'] = df['date'].dt.minute
df.head()

,date,user,message_only,year,month,day,hour,minute
0,2023-08-19 19:53:34,abhay,‎Messages and calls are end-to-end encrypted. ...,2023,August,19,19,53
1,2023-08-19 19:53:34,abhay,.\n,2023,August,19,19,53
2,2023-08-19 19:53:39,Abhishek jha_20233504,https://www.instagram.com/reel/Cv_67H3otmN/?ig...,2023,August,19,19,53
3,2023-08-19 19:55:03,abhay,‎video omitted\n,2023,August,19,19,55
4,2023-08-22 17:26:00,abhay,Abey hostel me light aa rahi hai kya\n,2023,August,22,17,26